server:
  port: 8889
  context-path: /ebitest

spring:
  datasource:
    platform: H2
    name: ebi-test-db
    url: jdbc:h2:mem:ebi-test-db
    data: classpath:/data/taxonomies.sql, classpath:/data/projects.sql
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          hbm2ddl:
            import_files: data/projects..sql

uiConfig:
  frontendUrl: http://localhost:4200
  enableCors: true

h2:
  console:
    enabled: true
    settings:
      web-allow-others: true

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs